// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA13nwjvSWvEwbZyZuUSiK7b38axSDo6qs',
    appId: '1:821062123671:web:25b47a2fb33dd726ad29d2',
    messagingSenderId: '821062123671',
    projectId: 'my-rentals-e8b34',
    authDomain: 'my-rentals-e8b34.firebaseapp.com',
    storageBucket: 'my-rentals-e8b34.appspot.com',
    measurementId: 'G-T29Y2EMPE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDA4DLBZI4EvZUeGd1POHp5ZGxI1120-Y',
    appId: '1:821062123671:android:b016b47b86815e1cad29d2',
    messagingSenderId: '821062123671',
    projectId: 'my-rentals-e8b34',
    storageBucket: 'my-rentals-e8b34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2JxWI_OhaBis3B0dpZKym8mD2SYZlrA',
    appId: '1:821062123671:ios:569c78540fe4051bad29d2',
    messagingSenderId: '821062123671',
    projectId: 'my-rentals-e8b34',
    storageBucket: 'my-rentals-e8b34.appspot.com',
    iosBundleId: 'com.example.myRentals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO2JxWI_OhaBis3B0dpZKym8mD2SYZlrA',
    appId: '1:821062123671:ios:569c78540fe4051bad29d2',
    messagingSenderId: '821062123671',
    projectId: 'my-rentals-e8b34',
    storageBucket: 'my-rentals-e8b34.appspot.com',
    iosBundleId: 'com.example.myRentals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA13nwjvSWvEwbZyZuUSiK7b38axSDo6qs',
    appId: '1:821062123671:web:f36df60764efc558ad29d2',
    messagingSenderId: '821062123671',
    projectId: 'my-rentals-e8b34',
    authDomain: 'my-rentals-e8b34.firebaseapp.com',
    storageBucket: 'my-rentals-e8b34.appspot.com',
    measurementId: 'G-Y1JEM6KVHJ',
  );
}
